config/routes.rb
Atlantis::Application.routes.draw do


  resources :meetings

  resources :placements

  # Theme Routes
  themes_for_rails

  get "change_log/index"

  # Root Routes
  root :to => 'dashboard#notes'
  resources :dashboard, :only => [:index, :xdocs]
  resource :change_log, :only => [:index]

  # Devise Routes
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # App Resources

  resources :notes, :only => :index

  resources :vteams do
    resources :opportunities
    resources :resource_vteam_allocations
    resources :vacations
    resources :notes
  end

  resources :leads do
    resources :opportunities
    resources :notes
  end
  resources :opportunities do
    resources :notes
  end
  resources :companies do
    resources :notes
  end
  resources :contacts do
    resources :notes
  end
  resources :placements do
    resources :notes
  end
  resources :meetings do
    resources :notes
  end


  resources :contacts, :companies, :opportunities, :testings, :resources

  match 'vteams/:id/resource_vteam_allocations/:rid/release' => "resource_vteam_allocations#release"
  match 'leads/details/:id' => "leads#details"
  match 'vteams/details/:id' => "vteams#details"
  match 'opportunities/details/:id' => "opportunities#details"
  match 'leads/details/:id' => "leads#details"
  match 'leads/:id/add_docs' => 'leads#add_docs'
  match 'placements/details/:id' => "placements#details"
  match 'vteams/:id/vacations/details/:rid' => "vacations#details"
  match 'meetings/details/:id' => "meetings#details"
  match 'vteams/:id/resource_vteam_allocations/details/:rid' => "resource_vteam_allocations#details"

  namespace :admin do
    match 'plugins' => 'plugins#index'
    match 'plugins/activate_plugin/:pid' => 'plugins#activate_plugin', :as=>:activate_plugin
    match 'plugins/deactivate_plugin/:pid' => 'plugins#deactivate_plugin', :as=>:deactivate_plugin

    match 'authorizations' => 'authorization#index'
    match 'authorizations/set_permissions/:action_to_do/:mode/:pid' => 'authorization#set_permissions'

    resources :users

    resources :meeting_types do
      as_routes
    end

    resources :address_types do
      as_routes
    end
    resources :contact_types do
      as_routes
    end
    resources :contact_directories do
      as_routes
    end
    resources :contact_statuses do
      as_routes
    end
    resources :phone_types do
      as_routes
    end
    resources :email_types do
      as_routes
    end
    resources :website_types do
      as_routes
    end
    resources :messenger_types do
      as_routes
    end
    resources :messenger_services do
      as_routes
    end
    resources :industries do
      as_routes
    end
    resources :countries do
      as_routes
    end
    resources :lead_types do
      as_routes
    end
    resources :lead_statuses do
      as_routes
    end
    resources :lead_sources do
      as_routes
    end
    resources :opportunity_types do
      as_routes
    end
    resources :opportunity_statuses do
      as_routes
    end
    resources :vteam_statuses do
      as_routes
    end
    resources :dev_centers do
      as_routes
    end
    resources :billing_modes do
      as_routes
    end
    resources :flags do
      as_routes
    end

    resources :note_types do
      as_routes
    end

    resources :add_users do
      as_routes
    end

    resources :resource_types do
      as_routes
    end

    resources :vacation_types do
      as_routes
    end

    resources :resource_billing_types do
      as_routes
    end

    resources :resources do
      as_routes
    end


    root :to => 'address_types#index'
  end
  match ':controller/:action'

  #  match '*a', :to => 'errors#routing'
  #  unless ActionController::Base.consider_all_requests_local
  #  end
  #resources :leads, :only => [:data_loader_status], :as => "autocomplete"
  #  resources :datagrid, :only => [:init] do
  #     collection do
  #       post "post_data"
  #     end
  #   end

  # The priority is based upon notes of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 30
  belongs_to :meeting_type
  belongs_to :user
  has_many :notes, :as => :parent
  belongs_to :updated_by, :foreign_key => "updated_by", :class_name => "User"

  validates :date_of_meeting, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  validates :location, :presence => true
  validates :attendees, :presence => true
  validates :minutes_of_meeting, :presence => true
  validates :meeting_type_id, :presence => true
  validates :user_id, :presence => true


  def title
    "Meeting on #{date_of_meeting}"
  end

  def note_title
    "Meeting on #{date_of_meeting}"
  end

  def meeting_start_time
    "#{start_time.hour}:#{start_time.min}"

  end

  def meeting_time_str
    seconds = self.meeting_time
    min, sec = seconds.divmod(60)
    hour, min = min.divmod(60)
    "#{hour.to_s.rjust(2, '0')}:#{min.to_s.rjust(2, '0')}"
  end

  def meeting_time
    end_time - start_time
  end

  def total_attendees_meeting_time
    (end_time - start_time) * attendees.to_s.split(",").count
  end

  def number_of_attendees
    attendees.to_s.split(',').count
  end

end

app/models/meeting_type.rb
class MeetingType < ActiveRecord::Base
  has_many :meetings

  def to_s
    self.meeting_type
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  load_and_authorize_resource
  helper :notes
  # GET /meetings
  # GET /meetings.xml
  def index

#    logger.debug filters.inspect
    @search = Meeting.search
    tabs = side_tabs_for_periods(:meetings)
    filters = filters_for_associations(:meetings)
    date_search = params[:search]

    if tabs.nil? and filters.nil?
      @meetings = Meeting
    elsif date_search.nil?
      @meetings = Meeting.order("created_at DESC").search(tabs.merge!(filters))
    else
      @meetings = Meeting.order("created_at DESC").search(tabs.merge!(filters).merge!(date_search))
    end

    @total_employees_meetings_time  = @meetings.all.sum(&:total_attendees_meeting_time)
    @total_meetings_time  = @meetings.all.sum(&:meeting_time)
    @meetings = @meetings.paginate(:per_page=>Meeting.per_page, :page=>params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xml  { render :xml => @meetings }
    end
  end


  def details
    @meeting = Meeting.find_by_id(params[:id])
    render "details"
  end


  # GET /meetings/1
  # GET /meetings/1.xml
  def show
    @meeting = Meeting.find(params[:id])
    @meeting.start_time.localtime
    @meeting.end_time.localtime

    respond_to do |format|
      format.html # show.html.erb

      format.xml  { render :xml => @meeting }

    end
  end

  # GET /meetings/new
  # GET /meetings/new.xml
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.xml
  def create
    @meeting = Meeting.new(params[:meeting])
    @meeting.user = current_user

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to(@meeting, :notice => 'Meeting was successfully created.') }
        format.xml  { render :xml => @meeting, :status => :created, :location => @meeting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.xml
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to(@meeting, :notice => 'Meeting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.xml
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to(meetings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_detail.html.erb
<div id="<%= @meeting.id %>" class="meeting-detail">
  <div id="close">
    <a class="thick-view-close" id="<%= @meeting.id %>" href=''><img src='/themes/white/images/icons/cross-active.png'></img></a>
  </div>
  <div id="meeting-left">
    <div id="age">
      <%= @meeting.age.to_s %>
    </div>
  </div>
  <div id="meeting-right">
    <div id="title-date">
      <h3><%= link_to @meeting.date_of_meeting, meeting_url(@meeting) %></h3>
    </div>
    <div id="meeting-situation">
      <div id="upper"><b>Date of Meeting:</b>
        <%= @meeting.date_of_meeting %></div>
      <div id="upper"><b>Meeting Type:</b>
        <%= @meeting.meeting_type %></div>
      <div id="upper"><b>Meeting start time:</b>
        <%= @meeting.meeting_start_time %></div>
      <div id="upper"><b>Meeting time:</b>
        <%= print_time(@meeting.meeting_time) %></div>
      <div id="upper"><b>Meeting Location:</b>
        <%= @meeting.location %></div>
      <div id="Lower"><b>Number Of Attendes:</b>
        <%= @meeting.number_of_attendees %></div>
    </div>
  </div>
  <div id="meeting-thick-view-options" class="thick-view-options">
    <%= options_menu do |m| %>
        <%= m.item link_to 'Show', meeting_path(@meeting) %>
        <%= m.item link_to 'Edit', edit_meeting_path(@meeting) %>
        <%= m.item link_to 'New Note', "meetings/#{@meeting.id}/notes/new", :class=>"display-new-note", :id=>@meeting.id %>
    <% end %>
  </div>
  <div class="notes-heading">
    <h3>Notes</h3>
  </div>
  <%= render :partial => 'shared/notes_list', :locals => {:notes=>@meeting.notes[0..2]} %>

</div>

app/views/meetings/_filter.html.erb
<%= quick_search("index", ["location", "attendees"],meetings_url) %>
<hr class="ver-gap"/>
<h2>Date Range</h2>
<hr class="ver-gap"/>
<%= simple_form_for  @search, :remote=>true do |f|   %>
  <%= f.input :date_of_meeting_greater_than_or_equal_to, :label=>'',:hint=>'From', :input_html=>{:class=>'datepicker'}  %>
  <%= f.input :date_of_meeting_less_than_or_equal_to, :label=>'',:hint=>'To', :input_html=>{:class=>'datepicker'}%>
  <%= f.button :submit, "Search" %>
<% end %>
<hr class="ver-gap"/>
<h2>Filter By</h2>
<hr class="ver-gap"/>

<%= filters_for_associations(:meetings, [:meeting_type]) %>
<hr class="ver-gap"/>

<div id="meetings_stats"></div>

app/views/meetings/_form.html.erb
<%= content_for :css do %>
  <%= theme_stylesheet_link_tag 'meetings/new' %>
<% end %>
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :date_of_meeting, :as=>:string, :label=>'Date', :input_html=>{:class=>'datepicker', :size=>20} %>
    <%= f.input :start_time, :as=>:time, :label=>'Start Time' %>
    <%= f.input :end_time, :as=>:time, :label=>'End Time'%>
    <%= f.input :location, :input_html=>{:size=>20} %>
    <%= f.association :meeting_type, :allow_blank=>false,:prompt =>false %>
    <%= f.input :attendees, :input_html=>{:rows=>7, :cols=>70} , :hint=>'Please specify persons seperated by commas'%>
    <%= f.input :minutes_of_meeting, :input_html=>{:rows=>7, :cols=>70} %>
  </div>

  <div class="actions">
    <%= f.button :submit, :class => 'button big', :input_html=>{} %> or
    <% if @meeting.new_record? %>
      <%= link_to 'Cancel', meetings_path, :class=>'big' %>
    <% else %>
      <%= link_to 'Cancel', meeting_url(@meeting), :class=>'big' %>
    <% end %>
  </div>
<% end %>

app/views/meetings/_list.html.erb
<div>
  <span><%= raw page_entries_info @meetings %></span>
</div>
<ul id="meetings_new_list" class="meetings_new_list">
  <% @meetings.each do |m| %>
    <li id="list-row-<%= m.id %>" class="meeting_new">
      <div class="type <%= m.meeting_type.to_s.underscore %>">
        <%= truncate("#{m.meeting_type}", :length => 12) %>
        <br/>

        <span class="small gray age"><%= m.age %></span>

      </div>
      <div class="name">
        <%= link_to m.date_of_meeting, meeting_url(m) %>
      </div>
      <div class="small gray">
        <%= "#{m.location}" %>
      </div>
      <br/>

      <div class="small gray">
        <%= "Attendies: #{m.number_of_attendees}" %>
      </div>

      <div class="actions">
        <%= options_menu do |o| %>
          <%= o.item link_to('Show', meeting_path(m.id)) %>
          <%= o.item link_to('Edit', edit_meeting_path(m.id)) %>
          <%= o.item link_to('New Note', "meetings/#{m.id}/notes/new", :class=>"display-new-note", :id=>m.id) %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<%= processed_pagination(@meetings) %>

app/views/meetings/_show_sidebar.html.erb
<%= show_signature(@meeting) %>

app/views/meetings/details.js.erb
openThickView("<%= params[:id] %>", "<%=escape_javascript(render :partial => 'detail') %>");

app/views/meetings/edit.html.erb
<%= content_for :header do %>
    <h1>Editing Meeting</h1>
<% end %>

<%= render 'form' %>

app/views/meetings/index.html.erb
<%= content_for :sidebar do %>
  <%= render :partial => 'filter'%>
<% end %>
<%= content_for :header do %>
 <h1>Meetings</h1>
 <%= link_to '<span class="ui-icon ui-icon-document">&nbsp;</span>New Meeting'.html_safe, new_meeting_url, :class=>'right', :style=>'margin-right:50px;' %>
<% end %>

<%= content_for :js do %>
 <%=javascript_include_tag "meetings/index" %>
 <%=javascript_include_tag "notes/global" %>
<% end %>

<%= content_for :css do %>
 <%= stylesheet_link_tag "meetings/index" %>
 <%= theme_stylesheet_link_tag 'notes/index' %>
<% end %>

<div id="meetingss_container" class="sidetabs-container">
  <div id="meeting_selector" class="sidetabs-tabs">
    <%=  side_tabs_for_periods(params[:controller].to_sym,['Today', 'This Week', 'This Month', 'This Year', 'Archives'] )%>
  </div>
  <div id="meetings" class="sidetabs-pane">
    
  </div>
</div>

app/views/meetings/index.js.erb
$('#meetings').html("<%=escape_javascript(render :partial => 'list') %>");
makeSameWidth( 'ul.list-headers', 'ul.list-row');
$('.pagination a').attr('data-remote', 'true');
$('dl.options').setId();
<% if params[:side_tab_period].nil? %>
  $("a.selected").removeClass("selected");
<%end%>
<% if params[:search].nil? %>
  $("#search_date_of_meeting_greater_than_or_equal_to").val("");
  $("#search_date_of_meeting_less_than_or_equal_to").val("");
<%end%>

$("#meetings_stats").html("<h2>Meetings Stats</h2>Total meeting time&nbsp;: <%= print_time(@total_meetings_time)%> <br/>Total employees time&nbsp;: <%= print_time(@total_employees_meetings_time)%> ");

<% unless params[:side_tab_period] %>
  $('div.sidetabs-tabs ul').find('[class="selected"]').removeClass('selected');
<% end %>

app/views/meetings/new.html.erb
<%= content_for :header do %>
    <h1>New Meeting</h1>
<% end %>

<%= render 'form' %>

app/views/meetings/show.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag "meetings/show" %>
    <%= theme_stylesheet_link_tag 'notes/index' %>
<% end %>
<% content_for :js do %>
    <%= javascript_include_tag 'notes/global' %>
    <%= javascript_include_tag "meetings/show" %>
<% end %>
<%= content_for :header do %>
    <h1><%= "#{@meeting.meeting_type} Meeting on #{l @meeting.date_of_meeting}" %></h1>
    <%= link_to 'Close', meetings_path, :class=>'button big right' %>
    <%= link_to 'Edit', edit_meeting_path(@meeting), :class=>'button big right' %>
<% end %>
<%= content_for :sidebar do %>
    <%= render :partial=>'show_sidebar' %>
<% end %>

<%= show_for @meeting do |s| %>
    <%= s.attribute :start_time, :format => :time %>
    <%= s.attribute :end_time, :format => :time %>
    <%= s.attribute :attendees %>
    <%= show_for_row "# of attendees", @meeting.number_of_attendees %>
    <%= show_for_row "Meeting Time", print_time(@meeting.meeting_time) %>
    <%= show_for_row "Employee Time", print_time(@meeting.total_attendees_meeting_time) %>

    <%= s.attribute :minutes_of_meeting %>
<% end %>

<hr class="clear"/>
<br/>
<div class="bottom-border">
  <h2 style="float:left;">Notes</h2>
  <%= if can?(:create, Note) then
          render_note_type_menu('Add New Note', meeting_path(@placement))
      end %>
</div>
<br class="clear"/>
<div class="notes-container">
</div>