config/routes.rb
Atlantis::Application.routes.draw do


  resources :meetings

  resources :placements

  # Theme Routes
  themes_for_rails

  get "change_log/index"

  # Root Routes
  root :to => 'dashboard#notes'
  resources :dashboard, :only => [:index, :xdocs]
  resource :change_log, :only => [:index]

  # Devise Routes
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # App Resources

  resources :notes, :only => :index

  resources :vteams do
    resources :opportunities
    resources :resource_vteam_allocations
    resources :vacations
    resources :notes
  end

  resources :leads do
    resources :opportunities
    resources :notes
  end
  resources :opportunities do
    resources :notes
  end
  resources :companies do
    resources :notes
  end
  resources :contacts do
    resources :notes
  end
  resources :placements do
    resources :notes
  end
  resources :meetings do
    resources :notes
  end


  resources :contacts, :companies, :opportunities, :testings, :resources

  match 'vteams/:id/resource_vteam_allocations/:rid/release' => "resource_vteam_allocations#release"
  match 'leads/details/:id' => "leads#details"
  match 'vteams/details/:id' => "vteams#details"
  match 'opportunities/details/:id' => "opportunities#details"
  match 'leads/details/:id' => "leads#details"
  match 'leads/:id/add_docs' => 'leads#add_docs'
  match 'placements/details/:id' => "placements#details"
  match 'vteams/:id/vacations/details/:rid' => "vacations#details"
  match 'meetings/details/:id' => "meetings#details"
  match 'vteams/:id/resource_vteam_allocations/details/:rid' => "resource_vteam_allocations#details"

  namespace :admin do
    match 'plugins' => 'plugins#index'
    match 'plugins/activate_plugin/:pid' => 'plugins#activate_plugin', :as=>:activate_plugin
    match 'plugins/deactivate_plugin/:pid' => 'plugins#deactivate_plugin', :as=>:deactivate_plugin

    match 'authorizations' => 'authorization#index'
    match 'authorizations/set_permissions/:action_to_do/:mode/:pid' => 'authorization#set_permissions'

    resources :users

    resources :meeting_types do
      as_routes
    end

    resources :address_types do
      as_routes
    end
    resources :contact_types do
      as_routes
    end
    resources :contact_directories do
      as_routes
    end
    resources :contact_statuses do
      as_routes
    end
    resources :phone_types do
      as_routes
    end
    resources :email_types do
      as_routes
    end
    resources :website_types do
      as_routes
    end
    resources :messenger_types do
      as_routes
    end
    resources :messenger_services do
      as_routes
    end
    resources :industries do
      as_routes
    end
    resources :countries do
      as_routes
    end
    resources :lead_types do
      as_routes
    end
    resources :lead_statuses do
      as_routes
    end
    resources :lead_sources do
      as_routes
    end
    resources :opportunity_types do
      as_routes
    end
    resources :opportunity_statuses do
      as_routes
    end
    resources :vteam_statuses do
      as_routes
    end
    resources :dev_centers do
      as_routes
    end
    resources :billing_modes do
      as_routes
    end
    resources :flags do
      as_routes
    end

    resources :note_types do
      as_routes
    end

    resources :add_users do
      as_routes
    end

    resources :resource_types do
      as_routes
    end

    resources :vacation_types do
      as_routes
    end

    resources :resource_billing_types do
      as_routes
    end

    resources :resources do
      as_routes
    end


    root :to => 'address_types#index'
  end
  match ':controller/:action'

  #  match '*a', :to => 'errors#routing'
  #  unless ActionController::Base.consider_all_requests_local
  #  end
  #resources :leads, :only => [:data_loader_status], :as => "autocomplete"
  #  resources :datagrid, :only => [:init] do
  #     collection do
  #       post "post_data"
  #     end
  #   end

  # The priority is based upon notes of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
  # GET /testings
  # GET /testings.xml
  def index
    #@testings = Testing.all

    if params[:start_date].nil?
      @start_date = Date.today
    else
      @start_date = params[:start_date].to_datetime
    end
    if params[:end_date].nil?
      @end_date = Date.today
    else
      @end_date = params[:end_date].to_datetime
    end
   
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @testings }
    end
  end

  # GET /testings/1
  # GET /testings/1.xml
  def show
    @testing = Testing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @testing }
    end
  end

  # GET /testings/new
  # GET /testings/new.xml
  def new
    @testing = Testing.new
    @testing.build_documents

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @testing }
    end
  end

  # GET /testings/1/edit
  def edit
    @testing = Testing.find(params[:id])
    #@testing.build_documents
  end

  # POST /testings
  # POST /testings.xml
  def create
    logger.debug "---------------------"
    logger.debug "---------------------"
    @testing = Testing.new(params[:testing])

    respond_to do |format|
      if @testing.save
        format.html { redirect_to(@testing, :notice => 'Testing was successfully created.') }
        format.xml { render :xml => @testing, :status => :created, :location => @testing }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @testing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /testings/1
  # PUT /testings/1.xml
  def update
    logger.debug "---------------------"
    logger.debug "---------------------"
    @testing = Testing.find(params[:id])

    respond_to do |format|
      if @testing.update_attributes(params[:testing])
        format.html { redirect_to(@testing, :notice => 'Testing was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @testing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /testings/1
  # DELETE /testings/1.xml
  def destroy
    @testing = Testing.find(params[:id])
    @testing.destroy

    respond_to do |format|
      format.html { redirect_to(testings_url) }
      format.xml { head :ok }
    end
  end

  private

  def days_in_month(year, month)
    (Date.new(year, 12, 31) << (12-month)).day
  end
  def days_between_dates(first, last)
    (YMD(last) - YMD(first))
  end

  def YMD(date)
    date.to_date.to_s.gsub("-", "").to_i
  end


end

app/helpers/testings_helper.rb
module TestingsHelper

  def tlist(object, &block)
    content_tag :ul, capture(TestingBuilder.new(object), &block)
  end

  class TestingBuilder
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::CaptureHelper
    include ActionView::Helpers::UrlHelper
    attr_accessor :object, :output_buffer

    def initialize(object)
      @object        = object
      @output_buffer = nil
    end

    def item(&block)
      if block_given?
        content_tag(:li, capture(self, &block))
      end
    end
  end

  def m(&block)
    "this block returns #{block.call}" if block_given?
  end
end

app/views/testings/_form.html.erb
<%= simple_form_for(@testing, :html => {:multipart => true}) do |f| %>
    <%= f.error_notification %>

    <div class="inputs">
      <%= f.input :title %>
    </div>

    <div class="inputs">
      <%= f.simple_fields_for :xdocs do |x| %>
          <% if x.object.new_record? %>
              <div class="inputs">
                <%= x.input :attachment, :as=>:file %>
                <%= x.input :title, :as=>:string %>
                <%= x.input :description, :as=>:text %>
                <%= x.input :type, :as=>:attachment_type %>
              </div>
          <% end %>
      <% end %>

    </div>

    <div class="actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/testings/edit.html.erb
<h1>Editing testing</h1>

<%= render 'form' %>

<%= link_to 'Show', @testing %> |
<%= link_to 'Back', testings_path %>

app/views/testings/index.html.erb
<h1>Listing testings</h1>
<%# day = 1 %>
<%# while day <= @days %>

<%# day+=1 %>
<%#= leads = Lead.where("created_at = ?", @created_at[day]) %>

<table>
  <tr>
    <th>Day Number</th>
    &nbsp;
    <th>Leads</th>
    &nbsp;
    <th>Vteams</th>
    &nbsp;
  </tr>
  <%# @start_date.upto @end_date do |d| %>
  <%# @leads = Lead.where("DATE(created_at) = DATE(?)", d).count %>
  <td><%#= @leads %></td>
  <%# end %>
  <%
     counts = Lead.count(
             :conditions => ["created_at >= ? AND created_at <= ?", @start_date.beginning_of_day, @end_date.end_of_day],
             :group      => "DATE(created_at)"
     )
     counts_array = []
     @start_date.upto @end_date do |d|
         counts_array << (counts[d.to_date] || 0)
     end

  %>
  <%= counts.inspect %>
  <%= counts_array.inspect %>
</table>
<br/>

<%= link_to 'New Testing', new_testing_path %>
<br/>

<%= m {
    1 + 2
} %>

<%= tlist "Raza" do |t| %>
    <%= t.item {
        "1"
    } %>
    <%= t.item {
        "2"
    } %>
    <%= t.item {
        "3"
    } %>
<% end %>

app/views/testings/new.html.erb
<h1>New testing</h1>

<%= render 'form' %>

<%= link_to 'Back', testings_path %>

app/views/testings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @testing.title %>
</p>
<p>
    <%= @testing.xdocs.first.attachment.url %>
</p>

<p>
    <%= @testing.xdocs.first.description %>
</p>


<%= link_to 'Edit', edit_testing_path(@testing) %> |
<%= link_to 'Back', testings_path %>