config/routes.rb
Atlantis::Application.routes.draw do


  resources :meetings

  resources :placements

  # Theme Routes
  themes_for_rails

  get "change_log/index"

  # Root Routes
  root :to => 'dashboard#notes'
  resources :dashboard, :only => [:index, :xdocs]
  resource :change_log, :only => [:index]

  # Devise Routes
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # App Resources

  resources :notes, :only => :index

  resources :vteams do
    resources :opportunities
    resources :resource_vteam_allocations
    resources :vacations
    resources :notes
  end

  resources :leads do
    resources :opportunities
    resources :notes
  end
  resources :opportunities do
    resources :notes
  end
  resources :companies do
    resources :notes
  end
  resources :contacts do
    resources :notes
  end
  resources :placements do
    resources :notes
  end
  resources :meetings do
    resources :notes
  end


  resources :contacts, :companies, :opportunities, :testings, :resources

  match 'vteams/:id/resource_vteam_allocations/:rid/release' => "resource_vteam_allocations#release"
  match 'leads/details/:id' => "leads#details"
  match 'vteams/details/:id' => "vteams#details"
  match 'opportunities/details/:id' => "opportunities#details"
  match 'leads/details/:id' => "leads#details"
  match 'leads/:id/add_docs' => 'leads#add_docs'
  match 'placements/details/:id' => "placements#details"
  match 'vteams/:id/vacations/details/:rid' => "vacations#details"
  match 'meetings/details/:id' => "meetings#details"
  match 'vteams/:id/resource_vteam_allocations/details/:rid' => "resource_vteam_allocations#details"

  namespace :admin do
    match 'plugins' => 'plugins#index'
    match 'plugins/activate_plugin/:pid' => 'plugins#activate_plugin', :as=>:activate_plugin
    match 'plugins/deactivate_plugin/:pid' => 'plugins#deactivate_plugin', :as=>:deactivate_plugin

    match 'authorizations' => 'authorization#index'
    match 'authorizations/set_permissions/:action_to_do/:mode/:pid' => 'authorization#set_permissions'

    resources :users

    resources :meeting_types do
      as_routes
    end

    resources :address_types do
      as_routes
    end
    resources :contact_types do
      as_routes
    end
    resources :contact_directories do
      as_routes
    end
    resources :contact_statuses do
      as_routes
    end
    resources :phone_types do
      as_routes
    end
    resources :email_types do
      as_routes
    end
    resources :website_types do
      as_routes
    end
    resources :messenger_types do
      as_routes
    end
    resources :messenger_services do
      as_routes
    end
    resources :industries do
      as_routes
    end
    resources :countries do
      as_routes
    end
    resources :lead_types do
      as_routes
    end
    resources :lead_statuses do
      as_routes
    end
    resources :lead_sources do
      as_routes
    end
    resources :opportunity_types do
      as_routes
    end
    resources :opportunity_statuses do
      as_routes
    end
    resources :vteam_statuses do
      as_routes
    end
    resources :dev_centers do
      as_routes
    end
    resources :billing_modes do
      as_routes
    end
    resources :flags do
      as_routes
    end

    resources :note_types do
      as_routes
    end

    resources :add_users do
      as_routes
    end

    resources :resource_types do
      as_routes
    end

    resources :vacation_types do
      as_routes
    end

    resources :resource_billing_types do
      as_routes
    end

    resources :resources do
      as_routes
    end


    root :to => 'address_types#index'
  end
  match ':controller/:action'

  #  match '*a', :to => 'errors#routing'
  #  unless ActionController::Base.consider_all_requests_local
  #  end
  #resources :leads, :only => [:data_loader_status], :as => "autocomplete"
  #  resources :datagrid, :only => [:init] do
  #     collection do
  #       post "post_data"
  #     end
  #   end

  # The priority is based upon notes of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/models/company.rb
class Company < ActiveRecord::Base

  cattr_reader :per_page
  @@per_page = 30

  belongs_to :industry
  belongs_to :user
  belongs_to :updated_by, :foreign_key => "updated_by", :class_name => "User"
  has_many :leads, :dependent => :destroy
  has_many :contact_company_profiles
  has_many :contacts, :through => :contact_company_profiles
  has_many :phones, :as => :phoneable, :dependent => :destroy
  has_many :websites, :as => :websiteable, :dependent => :destroy
  has_many :emails, :as => :emailable, :dependent => :destroy
  has_many :addresses, :as => :addressable, :dependent => :destroy
  has_many :notes, :as=>:parent

  accepts_nested_attributes_for :phones, :reject_if => proc { |a| a['phone_number'].blank? }
  accepts_nested_attributes_for :websites, :reject_if => proc { |a| a['url'].blank? }
  accepts_nested_attributes_for :emails, :reject_if => proc { |a| a['email'].blank? }
  accepts_nested_attributes_for :addresses, :reject_if => proc { |a| a['street'].blank? || a['country_id'].blank? }

  validates :title, :presence => true

  def to_s
    "#{title}"
  end

  def note_title
    self.title
  end

  scope :with_phones,
    lambda { |number|
    joins(:phones).where(:phone_number => number)
  }


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource
  helper :notes
  # GET /companies
  # GET /companies.xml

  def index

    tabs = side_tabs_for_alphabets(:companies)
    filters = filters_for_associations(:companies)

    if tabs.nil? and filters.nil?
      @companies = Company.paginate(:per_page=>Company.per_page, :page=>params[:page])
    else
      @companies = Company.order("title ASC").search(tabs.merge!(filters)).paginate(:per_page=>Company.per_page, :page=>params[:page])
    end
    
    respond_to do |format|
      format.html
      format.js
      format.json { render :json=>@companies.to_json(:include=>:industry) }
      format.xml { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=>@company.to_json(:include=>[:industry, :phones,]) }
      format.xml { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new
    @company.phones.build
    @company.websites.build
    @company.emails.build
    @company.addresses.build
    #@company.phones.phone_type.build
    respond_to do |format|
      format.html # new.html.erb
      format.js # new.html.erb
      format.xml { render :xml => @company }
    end
  end

  # GET /company/1/edit
  def edit

    session[:redirect] = request.referrer
    @company = Company.find(params[:id])
    if @company.phones.blank?
      @company.phones.build
    end
    if @company.websites.blank?
      @company.websites.build
    end
    if @company.emails.blank?
      @company.emails.build
    end
    if @company.addresses.blank?
      @company.addresses.build
    end
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company      = Company.new(params[:company])
    @company.user = current_user
    respond_to do |format|
      if @company.save
#        c = request.referrer.split("/")
#        logger.info "-----------------------------"
#        logger.debug request.referrer.split("/")
#        logger.debug c.length
#        logger.info "-----------------------------"
#        if c[3] == "contacts" or c[3] == "leads"
#        logger.info "inside comparison"
#        session[:company] = @company.id
#        end
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.js
        format.xml { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.js
        format.xml { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /company/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(session[:redirect], :notice => 'Company was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /company/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml { head :ok }
    end
  end

  def data_loader
    @company_data = Company.find(params[:id])
    render :partial => "data"
  end

  def quick_search


  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_data.html.erb
<h2><%= @company_data.title%></h2>

<fieldset><legend>Emails</legend>
  <% @company_data.emails.each do |email|%>
  <%= email.email %> <br />
  <% end %>
</fieldset>
<fieldset><legend>Websites</legend>
  <% @company_data.websites.each do |website|%>
    <%= website.url %><br/>
  <% end %>
</fieldset>
<fieldset><legend>Phones</legend>
  <% @company_data.phones.each do |phone|%>
    <%= phone.phone_number %> <br/>
  <% end %>
</fieldset>

app/views/companies/_filter.html.erb
<%= quick_search("index", ["title", "phone", "email"],companies_url) %>
<hr class="ver-gap" />

app/views/companies/_form.html.erb
<%= simple_form_for @company, :validations => {:options => {:errorClass => "bad-field"}} do |f| %>

    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this contact from being saved:</h2>
          <ul>
            <% @company.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div id='generalInfo'>
      <%= f.input :title, :input_html => {} %>
      <%= f.association :industry, :input_html=>{} %>

      <%= f.label :phones %>
      <div class="loopable-options">
        <div id="fields">
          <% c = 0 %>
          <%= f.simple_fields_for :phones do |f| %>
              <div id="field_<%= c %>" class="field">
                <%= f.association :phone_type, :hint=>'phone type', :input_html=>{}, :label=>false, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :phone_number, :label=>false, :input_html=>{:class=>"margin"}, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :_destroy, :as=>:hidden %>
              </div>
              <% c += 1 %>
          <% end %>
        </div>
      </div>

      <%= f.label :websites %>
      <div class="loopable-options">
        <div id="fields">
          <% c = 0 %>
          <%= f.simple_fields_for :websites do |f| %>
              <div id="field_<%= c %>" class="field">
                <%= f.association :website_type, :hint=>'website type', :input_html=>{}, :label=>false, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :url, :label=>false, :input_html=>{:class=>"margin"}, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :_destroy, :as=>:hidden %>
              </div>
              <% c += 1 %>
          <% end %>
        </div>
      </div>

      <%= f.label :emails %>
      <div class="loopable-options">
        <div id="fields">
          <% c = 0 %>
          <%= f.simple_fields_for :emails do |f| %>
              <div id="field_<%= c %>" class="field">
                <%= f.association :email_type, :hint=>'email type', :input_html=>{}, :label=>false, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :email, :label=>false, :input_html=>{:class=>"margin"}, :wrapper_html=>{:style=>'float:left;'} %>
                <%= f.input :_destroy, :as=>:hidden %>
              </div>
              <% c += 1 %>
          <% end %>
        </div>
      </div>
    </div>

    <h3>Address Details</h3>
    <div id="addressInfo">
      <%= f.simple_fields_for :addresses do |f| %>
          <div class="loopable-options">
            <div id="fields">
              <div id="field_0" class="field">
                <div style="display: block; float: left;">
                  <%= f.association :address_type, :input_html=>{} %>
                  <%= f.association :country, :input_html=>{:class=>'country', :id=>'country'} %>
                  <%= f.input :street, :input_html=>{:class=>'street', :id=>'street'} %>
                  <%= f.input :city, :input_html=>{:class=>'city', :id=>'city'} %>
                  <%= f.input :state, :input_html=>{:class=>'state', :id=>'state'} %>
                  <%= f.input :zip, :input_html=>{:class=>'zip', :id=>'zip'} %>
                  <%= f.input :lat, :as=>:hidden, :input_html=>{:class=>'lat', :id=>'lat'} %>
                  <%= f.input :lng, :as=>:hidden, :input_html=>{:class=>'lng', :id=>'lng'} %>
                  <%= f.input :_destroy, :as=>:hidden %>
                </div>
                
              </div>
            </div>
          </div>
      <% end %>
    </div>
    <br/>
    <div class="actions">
    <%= f.button :submit, :class=>'button big' %> <span style="vertical-align: bottom">or</span>
    <%= link_to 'Cancel', request.referrer , :class=>'big' %>
    </div>
<% end %>

app/views/companies/_list.html.erb
<div>
  <span><%= raw page_entries_info @companies %></span>
</div>
<ul id="companies_new_list" class="companies_new_list">
  <% @companies.each do |c| %>
    <li id="list-row-<%= c.id %>" class="company_new">

      <div class="type all">
        <%= c.age %>
      </div>

      <div class="name">
        <%= link_to c.title, company_url(c) %>
      </div>
      <br/>

      <div class="contact-detail small gray">
        <% if c.emails.count > 0 %>
          <a href="mailto:<%= c.emails.first %>"><span class="ui-icon ui-icon-mail-closed">&nbsp;</span><span class="gray small"><%= c.emails.first %></span></a>
        <% end %>
        <% if c.phones.count > 0 %>
          <span class='ui-icon ui-icon-person'>&nbsp;</span><span class="gray small"><%= c.phones.first %></span>
        <% end %>
      </div>

      <div class="actions">
        <%= options_menu do |o| %>
          <%= o.item link_to('Show', company_path(c.id)) %>
          <%= o.item link_to('Edit', edit_company_path(c.id)) %>
          <%= o.item link_to('New Note', "companies/#{c.id}/notes/new", :class=>"display-new-note", :id=>c.id) %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<%= processed_pagination(@contacts) %>

app/views/companies/_min_form.html.erb
<% if request.referrer.split("/")[3] == "leads" %>
<% url = "leads" %>
<% elsif request.referrer.split("/")[3] == "contacts" %>
<% url = "contacts" %>
<% end %>
<%= simple_form_for @company,:url=>{:controller=>url} do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this contact from being saved:</h2>
          <ul>
            <% @company.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.input :title, :input_html=>{:size=>'25',:class=>'fix'} %>
    <%= f.association :industry, :input_html=>{:class=>'auto fix'} %>
    <%= f.simple_fields_for :phones do |f| %>
        <%= f.association :phone_type, :label=>"Phone Type", :input_html=>{:class=>'auto fix'} %>
        <%= f.input :phone_number, :label=>"Phone Number", :input_html=>{:size=>'15',:class=>'fix'} %>
    <% end %>
    <div class="actions">
    <%= f.button :submit, :class=>'button big' %>
    </div>

<% end %>

app/views/companies/_show_compact.html.erb
<%= show_for company do |l| %>
  <dl class="wrapper">
    <dt class="label"><span class="ui-icon ui-icon-battery-0">&nbsp;</span></dt>
    <dd class="content"><%= link_to company.title, company_url( l.object ) %> </dd>
  </dl>

  <%#= l.attribute :title, :label=>"<span class='ui-icon ui-icon-battery-0'>&nbsp;</span>".html_safe %>
  <% if l.object.phones.present? %>
    <%= l.association :phones, :to_sentence=>true, :label=>"<span class='ui-icon ui-icon-contact'>&nbsp;</span>".html_safe %>
  <% end %>

  <% if l.object.emails.present? %>
    <%= l.association :emails, :to_sentence=>true, :label=>"<span class='ui-icon ui-icon-mail-closed'>&nbsp;</span>".html_safe %>
  <% end %>

  <% if l.object.websites.present? %>
    <%= l.association :websites, :to_sentence=>true, :label=>"<span class='ui-icon ui-icon-link'>&nbsp;</span>".html_safe %>
  <% end %>

  <% if l.object.addresses.present? %>
    <%= l.association :addresses, :to_sentence=>true, :label=>"<span class='ui-icon ui-icon-home'>&nbsp;</span>".html_safe %>
  <% end %>

  
<% end %>

app/views/companies/_show_sidebar.html.erb
<%= quick_search("show", ["note-type", "posted-by"]) %>

<% if @company.contacts.present? %>


  <h2>Contacts</h2>
  <div class="contact_list_detail" >

    <% @company.contacts.each do |contact| %>

      <%= render :partial => 'contacts/show_compact',
        :locals=>{ :contact=>contact, :list => "true" } %>
    <% end %>
  </div>
<%  end %>


<%= show_signature @company %>

app/views/companies/create.js.erb
<% if (@company.errors.any?) %>
        alert('<%= escape_javascript( @company.errors.full_messages.to_s ) %>');
<% else %>
    $('#new_company_dialog').dialog('close');
    $('#lead_company').val("<%= "#{@company.title}" %>");
    var a = $('#lead_company').parent("div").append("<a id='<%=@company.id%>' href='/companies/<%=@company.id%>/edit'>Edit</a>");
    $('#lead_company_id').val(<%= @company.id %>);
    $('#lead_title').focus();
<% end %>

app/views/companies/edit.html.erb
<%= content_for :css do %>
  <%=stylesheet_link_tag "companies/new"%>
<%end%>
<%= content_for :js do %>
  <%=javascript_include_tag "companies/new"%>
<%end%>
<%= content_for :header do %>
<div id="errors"></div>
  <h1>Editing Company</h1>
    
<% end %>
<%= content_for :sidebar do %>
    <%= render 'sidebar' %>
<% end %>

<%= render 'form' %>

app/views/companies/index.html.erb
<%= content_for :js do %>
 <%=javascript_include_tag "companies/index" %>
 <%=javascript_include_tag "notes/global" %>
<% end %>

<%= content_for :css do %>
 <%= stylesheet_link_tag "companies/index" %>
 <%= theme_stylesheet_link_tag 'notes/index' %>
<% end %>

<%= content_for :sidebar do %>
 <%= render :partial => 'filter'%>
<% end %>

<%= content_for :header do %>
 <h1>Companies</h1>
 <%= link_to '<span class="ui-icon ui-icon-document">&nbsp;</span>New Company'.html_safe, new_company_url, :class=>'right', :style=>'margin-right:50px;' %>
<% end %>

<div id="companies_container" class="sidetabs-container">
  <div id="companies_selector" class="sidetabs-tabs">
   <%=  side_tabs_for_alphabets(:companies) %>
  </div>
  <div id="companies" class="sidetabs-pane">
  </div>
</div>

app/views/companies/index.js.erb
$('#companies').html("<%=escape_javascript(render :partial => 'list') %>");
makeSameWidth( 'ul.list-headers', 'ul.list-row');
$('.pagination a').attr('data-remote', 'true');

app/views/companies/new.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'companies/new'  %>
<% end %>
<%= content_for :js do %>
  <%= javascript_include_tag 'companies/new'  %>
<% end %>

<%= content_for :header do %>
<div id="errors"></div>
  <h1>Create New Company</h1>
<% end %>

<%= content_for :sidebar do %>
    <%= render 'sidebar' %>
<% end %>

<%= render 'form' %>

app/views/companies/new.js.erb
$('<div />').attr('id','new_company_dialog').appendTo('body');
$('#new_company_dialog').html('');
$('#new_company_dialog').attr('title', 'Create New Company');

$('#new_company_dialog').html('<%= escape_javascript( render :partial=>'min_form') %>');
$('#new_company_dialog').dialog({
  width:435,
  height:250
});
$('#company_industry_id').focus();

app/views/companies/show.html.erb
<%= content_for :css do %>
    <%= stylesheet_link_tag "companies/show" %>
    <%= theme_stylesheet_link_tag 'notes/index' %>
<% end %>
<%= content_for :js do %>
    <%= javascript_include_tag "notes/global" %>
    <%= javascript_include_tag 'companies/show' %>
    <%= javascript_include_tag "jquery.collapsorz_1.1" %>
<% end %>
<%= content_for :sidebar do %>
    <%= render :partial=>'show_sidebar' %>
<% end %>

<%= content_for :header do %>
    <h1><%= @company.title %></h1>
    <%= link_to 'Close', companies_path, :class=>'button big right' %>
    <%= link_to 'Edit', edit_company_path(@company), :class=>'button big right' %>
<% end %>

<%= show_for @company do |c| %>

    <% unless @company.industry.blank? %>
        <%= c.association :industry %>
    <% end %>

    <% if @company.phones.exists? %>
        <%= c.association :phones, :to_sentence=>true %>
    <% end %>

    <% unless @company.emails.blank? %>
        <%= c.association :emails, :to_sentence=>true %>
    <% end %>

    <% unless @company.websites.blank? %>
        <%= c.association :websites, :to_sentence=>true %>
    <% end %>

    <% unless @company.addresses.blank? %>

        <% unless @company.addresses.first.country_id.nil? %>
            <%= c.association :addresses, :to_sentence=>true %>
        <% end %>

    <% end %>

<% end %>
<hr class="clear"/>
<br/>
<div class="bottom-border">
  <h2 style="float:left;">Notes</h2>
  <%= if can?(:create, Note) then
          render_note_type_menu('Add New Note', company_path(@company))
      end %>
</div>
<br class="clear"/>
<div class="notes-container"></div>